import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'back end/instalacion',
    'back end/Estructura del Proyecto', 
    {
      type: 'category',
      label: 'Endpoints',
      items: [
        'back end/endpoints/login', 'back end/endpoints/usuario',
        'back end/endpoints/solicitud', 'back end/endpoints/colaborador',
        'back end/endpoints/puesto', 'back end/endpoints/telefono', 
        'back end/endpoints/documentos', 'back end/endpoints/auditoria', 
      ],
    },
    'back end/Modelos y Esquemas de Base de Datos',  
    'back end/Middleware',
    'back end/integracion-docker',
    'back end/Referencias y Recursos Adicionales',
  ],
  sideBar2: [
    'front end/instalacion',
    'front end/Estructura',
  ]
   
};

export default sidebars;
